# Generated by Django 5.1.6 on 2025-06-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_address1_shippingaddress_shipping_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
