# Generated by Django 5.1.6 on 2025-07-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_order_date_shippied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_shippied',
            new_name='date_shipped',
        ),
    ]
