# Generated by Django 5.1.6 on 2025-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_remove_order_shipped_order_date_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
