# Generated by Django 5.1.6 on 2025-09-17 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_order_cancellation_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='payment_ord_status_4b9fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-date_ordered'], name='payment_ord_date_or_a129a0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-date_shipped'], name='payment_ord_date_sh_096bc4_idx'),
        ),
    ]
