# Generated by Django 5.1.6 on 2025-09-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_order_payment_ord_status_4b9fa9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.15, help_text='Commission rate as decimal (e.g., 0.15 for 15%)', max_digits=4),
        ),
    ]
