# Generated by Django 5.1.6 on 2025-09-17 10:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_orderitem_commission_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.15'), help_text='Commission rate as decimal (e.g., 0.15 for 15%)', max_digits=4),
        ),
    ]
