# Generated by Django 5.2.6 on 2025-09-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_remove_orderitem_seller_logo_orderitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
