# Generated by Django 5.2.6 on 2025-10-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_order_phone_number_shippingaddress_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactfundtransaction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Transactions for the current active project fund goal.'),
        ),
    ]
