# Generated by Django 5.2.6 on 2025-12-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_impactfundtransaction_is_active'),
        ('store', '0011_quoterequest_sellerquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='quote_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.quoterequest'),
        ),
    ]
