# Generated by Django 5.2.6 on 2025-12-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_notification_quote_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Transaction ID or Reference', max_length=100, null=True),
        ),
    ]
