# Generated by Django 5.2.6 on 2025-12-16 00:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_alter_order_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.08'), help_text='Decimal (0.08 = 8%)', max_digits=5),
        ),
    ]
