# Generated by Django 5.1.6 on 2025-09-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_profile_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
