# Generated by Django 5.2.6 on 2025-12-06 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_impactfundtransaction_is_active'),
        ('store', '0010_product_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('location_city', models.CharField(help_text='e.g. Lusaka, Ndola', max_length=100)),
                ('location_province', models.CharField(default='Lusaka', max_length=100)),
                ('project_type', models.CharField(choices=[('residential', 'Residential (Home)'), ('commercial', 'Commercial (Office/Shop)'), ('agricultural', 'Agricultural (Farm/Irrigation)'), ('industrial', 'Industrial')], default='residential', max_length=20)),
                ('system_type', models.CharField(choices=[('backup', 'Backup System (Load Shedding only)'), ('off_grid', 'Off-Grid (No ZESCO connection)'), ('hybrid', 'Hybrid (Solar + Grid + Battery)'), ('grid_tie', 'Grid-Tie (Save Bill, No Battery)'), ('unsure', 'I am not sure')], default='hybrid', max_length=20)),
                ('daily_energy_usage_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Average daily usage in kWh (check your ZESCO bill)', max_digits=10, null=True)),
                ('current_voltage', models.CharField(blank=True, help_text='e.g., Single Phase (220V) or Three Phase (380V)', max_length=50, null=True)),
                ('appliances_to_run', models.TextField(help_text='List key appliances (e.g., 1 Fridge, 5 Lights, 1 TV, Borehole Pump)')),
                ('roof_type', models.CharField(blank=True, help_text='e.g., Metal Sheet (ITR), Tile, Concrete Slab', max_length=100, null=True)),
                ('budget_range', models.CharField(blank=True, help_text='e.g., K20,000 - K50,000', max_length=100)),
                ('timeline', models.CharField(choices=[('immediate', 'Immediately'), ('1_month', 'Within 1 month'), ('3_months', '1-3 Months'), ('planning', 'Just Planning/Budgeting')], default='1_month', max_length=20)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('processing', 'Processing'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('components_summary', models.TextField(help_text='Summary of panels, inverter, battery brands/sizes')),
                ('installation_included', models.BooleanField(default=True)),
                ('warranty_terms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_quotes', to='store.quoterequest')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_submitted', to='payment.seller')),
            ],
        ),
    ]
