# Generated by Django 5.2.6 on 2025-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Lay-By', 'Lay-By'), ('Payment Plan', 'Payment Plan')], default='Cash', max_length=20),
        ),
    ]
